version: '1'

services:
  angular-demo:
    environment:
      - NODE_ENV=development
      - PORT=80
      - DB_AUTHENTICATE=false
    build:
      context: .
      dockerfile: server.dockerfile
    container_name: ngular-demo
    ports:
      - '9090:8080'
    networks:
      - node-network
networks:
  node-network:
    driver: bridge
